### PR TITLE
8.0 compatibility

### PR DESCRIPTION
**Pull request by jasongrout**
This PR aims to have the codebase compatible with ipywidgets 7 and ipywidgets 8.

This also drops support for python 3.6, which has reached EOL.

### CODE REVIEW

**Comment by jasongrout** [comment]
[c154430](https://github.com/jupyter-widgets/jupyterlab-sidecar/pull/86/commits/c154430353d51965643949beddbffd47ed826e6c) should be deleted after ipywidgets 8 is released - it's only there to force npm to choose the prerelease versions so we can test ipywidgets 8.

**Comment by mwcraig** [comment]
@jasongrout - This works for me locally now. Adding the dependency on `css-loader` fixed the odd error I showed you on Friday.

I have not fixed [this use of `ManagerBase`](https://github.com/jupyter-widgets/jupyterlab-sidecar/blob/master/tests/src/utils.spec.ts#L50) in the sidecar tests. When I tried to change it following the migration guide I got an error that `Type 'ManagerBase' is not generic.`

**Comment by martinRenou** [comment]
> When I tried to change it following the migration guide I got an error that Type 'ManagerBase' is not generic

This can be fixed by removing the `<HTMLElement>` part: `ManagerBase<HTMLElement>` -> `ManagerBase`

**Comment by mwcraig** [comment]
> This can be fixed by removing the <HTMLElement> part: ManagerBase<HTMLElement> -> ManagerBase

Thanks, done. One of these days I should really try to learn typescript...

**Comment by mwcraig** [comment]
No idea why the extension isn't being installed...there was a compilation issue caused by openssl3 dropping support for md4 hashes, see https://stackoverflow.com/questions/69719601/getting-error-digital-envelope-routines-reason-unsupported-code-err-oss

**Comment by eteq** [comment]
Poking about the status of this one. Any sense whether this is a deep problem vs "just need to convince the CI to reognize the right version"?

**Comment by jasongrout** [comment]
I manually checked also that I could build the python package and install it with ipywidgets 7 and ipywidgets 8 and it worked correctly for the readme example.

**Comment by jasongrout** [comment]
We just released 0.5.2, which enables ipywidgets 8 support.

**Pull request merged**
